### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by patrickb8man** [flerovii/nanoboy#1]
I don't know if this is due to my computer, but I do know that it's related to OpenAL.

When I load a rom, I hear a single beep and then silence for the rest of the game. I know it's not related to the rom since the audio inspector is lighting up and working as expected.
I've attempted to look into it and I suspect it's something to do with [OpenAL not processing buffers in ALSoundOut.cs](https://github.com/fredericmeyer/nanoboy/blob/master/nanoboy/nanoboy/Core/Audio/Backend/OpenAL/ALSoundOut.cs#L117), as the if statement is never true after a second of play.

**Comment by fredericmeyer** [comment]
Hi and sorry for the late response! You're right,  this is propably related to the OpenAL code. This is my first time working with OpenAL, especially dealing with audio generated on the fly. I'll look into this as soon as I can.
